services:
  postgres:
    image: postgres:16
    container_name: telco-postgres
    environment:
      POSTGRES_DB: telco
      POSTGRES_USER: telco
      POSTGRES_PASSWORD: telco123
    ports:
      - "5432:5432"
    volumes:
      - telco_pg_data:/var/lib/postgresql/data

volumes:
  telco_pg_data:
