# --- PostgreSQL (dev) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/telco
spring.datasource.username=${TELCO_DB_USER:telco}
spring.datasource.password=${TELCO_DB_PASS:telco123}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA ---
# For first iteration, keep update for speed. We'll replace with Flyway later.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# --- Logging (optional) ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
